### ISSUE TITLE
Distinguish between user's and public Tales

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#31] opened 2017-04-27 17:58 UTC
Right now it's not possible to see whether a tale presented in the 'Home' or 'Explore/Published Tales' is actually public, or is not public and user has access to it, without clicking on 'details'. We should provide a distinct view for both kinds of tales.

**Comment by abrinckm** [comment] 2017-11-07 17:48
duplicate of #99 and #100. Please close

**Closed** 2017-11-07 17:57 UTC
