### ISSUE TITLE
Deleted instances still show up in Launched Tales tab

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/dashboard#213] opened 2018-07-27 21:13 UTC
Steps to reproduce:

1. Launch a few Tales (4 should be enough)
2. Delete them one by one from the right-hand side menu
3. Change tab

Result:
Usually at least one of the instances will pop back up in the menu. Our working theory is that, widget doesn't wait for 200 from DELETE, and `GET /instance` called upon switching view is still able to pick it up.

Expected result:
Tales are removed from the panel, when they're actually gone from the backend, not by just modifying ember state.

**Comment by swyngaard** [comment] 2018-07-30 15:59
This error is related to the error I mentioned in #185 . I believe the error stems from transitioning routes after deleting an instance. I still need to report the bug to the Ember devs.

**Comment by craig-willis** [comment] 2018-07-30 19:28
As discussed with @cyberdante on dev call, is there a workaround in the meantime?

**Comment by cyberdante** [comment] 2018-09-13 02:14
This is unfortunately still outstanding.

**Comment by bodom0015** [comment] 2018-12-13 17:38
As @ThomasThelen suggested, this appears to be a side-effect of the asynchronous nature of deleting a container instance. One way to help this issue from our end might be to add a new DELETING state to [`InstanceStatus`](https://github.com/whole-tale/girder_wholetale/blob/master/server/constants.py#L37-L50).

This way, when the DELETE `/instance/:id` endpoint is hit we can instantly mark the instance as `DELETING`, signaling that the instance will soon be deleted. We can then add logic to the UI that can filter out any instances in this state. Girder/Docker can take as long as they need to clean things up, and the user will no longer be offered that instance in the UI as if it were still valid.

Would this sound like an agreeable solution, if I can get a working implementation?

**Comment by bodom0015** [comment] 2018-12-20 20:46
I have so far been unable to reproduce this reliably, but found an edge case that may possibly be related to this bug. I figured I should post it here for good measure.

In my case:
1. On the Tale Tab Selector, I used the Tale Metadata Tab to edit the name of a tale and Save
2. After editing the name, I launched a new instance from it immediately (e.g. did not refresh)
    * BUG: the instance was given the old (incorrect) name, instead of the new one
3. Killed the instance I just launched
4. Refreshed until the instance was gone
5. Launched another instance from the renamed tale
    * Instance now had the new (correct) name

Repeating these steps, I am unable to get an instance to launch with the stale/old/incorrect name, so it's unclear if this is directly related, but I suspect this deletion behavior may have played a role.

**Comment by ThomasThelen** [comment] 2019-02-15 18:16
While testing for 0.6 I reliably ran across this issue on stage. The Tale is removed from the panel however, after a page refresh it still appears.

I'm not sure if there is a clean fix for this; one hack would be to 

```
while instanceNotDeleted
   deleteInstance()
```

**Comment by bodom0015** [comment] 2019-07-24 21:36
There is no longer a `tale-instances` panel. Closing.

**Closed by bodom0015** 2019-07-24 21:36 UTC
Labels: area/ui-ux, kind/bug
