### ISSUE TITLE
Failure to re-login with Google Id

### ISSUE THREAD

**Issue by ludaesch** [whole-tale/dashboard#28] opened 2017-04-13 18:02 UTC
First I was still successfully logged in from a prior attempt (at UT Austin I think).
Then I logged out to see how the landing page looks like.
But after I tried to re-login via Google Id (not Globus .. as before?), I only saw the "inside page" (i.e., after login) very briefly; a mere flicker; and then I was sent back to the login page again.
The help says: "click below" but there's no link to click below.
<img width="1247" alt="wt-login-bug" src="https://cloud.githubusercontent.com/assets/7769871/25017447/79bd87f8-2049-11e7-9f2a-2cd950871380.png">

**Comment by ian-taylor** [comment] 2017-04-13 18:29
I figured out what is causing this and we're looking into it. As a workaround, do the following:

- go to the cookies on your browser
- delete the cookie named "girderToken" and then reload the page

you'll be able to log in ok then.  The issue is that the girderToken is not being deleted on log out even though the user is logged out and when there is an invalid token, the system does not work properly. We're working on this issue now.

**Comment by ian-taylor** [comment] 2017-04-14 15:04
This issue is fixed now. Please let us know if there any more issues.

**Closed by ian-taylor** 2017-04-14 15:04 UTC
