### ISSUE TITLE
Notification stream shows stale notifications

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#186] opened 2018-07-03 19:25 UTC
After launching a tale go to the Manage page and register a dataset. Notifications start to display unrelated to the registration.

To repeat:
* Browse > Launch example Rstudio tale
* Manage > Add Dataset > 10.5065/D6862DM8

**Comment by craig-willis** [comment] 2018-07-17 16:50
As noted on the call yesterday, there are other problems with the notification on the Manage page. Using the same dataset as above, you will see multiple notifications popping up slowly, with no indication that the register is complete.  Also I've frequently “Error Registering Object [Object object]” notifications during this step.

**Comment by ThomasThelen** [comment] 2018-07-17 20:45
It sounds like there are two issues here-one is grabbing old notifications, and another that we need to beef up communication with the user during data registration.

Right now we close the registration dialog after `Register` is clicked. I think one way to solve this would be to keep the dialog open, and put a spinner on the `Register` button. In addition, it might be helpful to display the error on the dialog.

One issue with this (and dialogs in general) is that if the user closes it, they'll have no indication that data is still registering. We could keep the notification stream open and only show the messages that registration has begun and finished-which the user will see even if the dialog is closed.

**Comment by cyberdante** [comment] 2018-07-18 13:35
@craig-willis: This is also a backend issue, apparently. If that's the case, it should be reported to Girder, @Xarthisius

**Comment by Xarthisius** [comment] 2018-07-18 13:36
@cyberdante that's not backend. See my comment above

**Comment by cyberdante** [comment] 2018-07-18 13:43
@abrinckm ^^^

**Comment by Xarthisius** [comment] 2018-07-18 13:47
BTW, looks like @ThomasThelen fixed it in https://github.com/whole-tale/dashboard/commit/85f3eac14b22eb7eb5d64cbf7eb25b12435b579a

**Comment by abrinckm** [comment] 2018-07-18 14:46
Okay, I only skimmed the issue. Let me test Tommy's fix and see if I can reproduce.

**Comment by craig-willis** [comment] 2018-07-18 14:57
@ThomasThelen  @abrinckm   Should I create a separate issue for https://github.com/whole-tale/dashboard/issues/186#issuecomment-405651130?  As Tommy noted, this is not directly related to the stale issue problem.

**Comment by abrinckm** [comment] 2018-07-18 15:00
So the two issues remaining are: errors show `[Object object]` and we don't have any indication when a job has finished?

**Comment by craig-willis** [comment] 2018-07-18 15:09
Here's my take on the feedback from Kyle and discussion on Monday. @Xarthisius @ThomasThelen may have additional thoughts:

* It's hard to understand the status of registration (is it in progress? is it done? did it fail?). Also, the user likely cares mainly about overall status, not the specific event notifications. 
* It's not just that errors show `[Object object]`, but more that there are errors and I as a user don't know what to do about them. If there are errors, did the registration fail? How do we recover?

**Comment by ThomasThelen** [comment] 2018-07-18 17:53
@craig-willis Your assessment seems correct. 

As for the status of registration-note everything below is specific to DataONE. The tricky part is knowing how much is left to register. The function that handles this is recursive, with the upper bound not known (see [register_DataONE_resource](https://github.com/whole-tale/girder_wholetale/blob/master/server/rest/harvester.py#L39)).

At one point we were planning on a quick start-and part of it had a file listing (see below) so that the user could see what was happening. I wrote an endpoint, `GET /repository/listFiles` that will go ahead and ask DataONE what the files are in _all_ of the nested packages. Then, as files are being registered you can tap into the notification stream and get the name of the file that just came through. That would be enough information to to put a green checkbox where the "Complete" text is.

I actually have this somewhere on disk-and there's a good chance that it's in one of the dashboard branches. I'll go hunt it down and we can discuss this further. If I recall correctly I _didn't_ have the files in a nested hierarchy, most most of everything else should be. 

![screen shot 2018-07-18 at 10 30 42 am](https://user-images.githubusercontent.com/9289652/42897790-f63bd1c6-8a75-11e8-8648-6dafc77b1c03.png)


As for the second issue. It looks like JS tried to parse something from the backend and couldn't figure it out-or we're sometimes incorrectly parsing the notification stream.

**Comment by ThomasThelen** [comment] 2018-07-18 19:32
Also @craig-willis as per your comment above, I think the data registration stuff should go in another issue.

**Comment by ThomasThelen** [comment] 2018-11-14 22:20
This has been fixed in the referenced issues above (#180 and 85f3eac)

**Closed by ThomasThelen** 2018-11-14 22:20 UTC
Labels: area/ui-ux, bug, kind/bug
