### ISSUE TITLE
Manage > Data local storage problem in v0.6.rc2 

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#422] opened 2019-02-21 08:29 UTC
I'm seeing two issues on the v0.6rc2 manage data page:
1. Registered dataset doesn't appear without refresh
2. Local storage currentFolderId is undefined, resulting in 400 errors

Test case:
1. https://dashboard.stage.wholetale.org
2. Manage > Data remove any existing registered datasets
3. Register dataset doi:10.5065/D6TB1525
4. Note: Dataset doesn't appear in folder after registration
5. Select Home then Data. Dataset should appear
6. Select Run then Select Manage

```
GET https://girder.stage.wholetale.org/api/v1/folder/undefined 400 (Bad Request)
girder.stage.wholetale.org/api/v1/item?limit=0&folderId=undefined&reload=true:1 GET https://girder.stage.wholetale.org/api/v1/item?limit=0&folderId=undefined&reload=true 400 (Bad Request)
girder.stage.wholetale.org/api/v1/folder?limit=0&parentId=undefined&parentType=folder&reload=true:1 GET https://girder.stage.wholetale.org/api/v1/folder?limit=0&parentId=undefined&parentType=folder&reload=true 400 (Bad Request)
```

Under local storage, there is no `currentFolderId` key.

**Comment by bodom0015** [comment] 2019-02-21 16:22
Since https://github.com/whole-tale/dashboard/pull/414 has already been merged, I take it that those changes did not fix this issue?

**Comment by bodom0015** [comment] 2019-02-21 16:49
Slimmer reproducible test case if you already have a dataset registered:
1. Navigate to Manage > Data
2. Remove a dataset
3. Navigate to Run
4. Attempt to navigate back to Manage

In this case, `"undefined"` is a literal string instead of the `undefined` type, breaking normal JavaScript conventions. The null-checking here is therefore inadequate: https://github.com/whole-tale/dashboard/blob/master/app/services/internal-state.js#L42

My fault for not noticing this anti-pattern later on in the same file (see `workspaceId` on line 234) and correcting it sooner.

I will make a PR to fix this.

**Closed** 2019-03-05 20:05 UTC
