### ISSUE TITLE
File browser context doesn't change when switching instances

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#380] opened 2019-02-07 19:05 UTC
Test case:
1. Create Tale A and Tale B
2. Upload file to Tale A workspace, leave Tale B empty
3. Select Tale A > Files > tale workspace (note file is present)
4. Select Tale B  from launched instances. Note, Tale A workspace is still displayed

Expected behavior:
* Workspace for Tale B is displayed

Note:  Interact and metadata tabs don't seem to have a problem.

**Comment by bodom0015** [comment] 2019-02-13 18:59
This should now be fixed, since #379 has been merged.

That PR contained the following change to resync the displayed file data when the selected Tale changes:
https://github.com/whole-tale/dashboard/pull/379/files#diff-b22ebb3f6d2f7b177bc2c4fbb882b304R101

**Comment by ThomasThelen** [comment] 2019-02-15 00:19
Confirmed that this is fixed on stage

**Closed** 2019-02-15 22:27 UTC
