### ISSUE TITLE
Deleting a Running Tale Shows Running Instance

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#495] opened 2019-06-17 19:50 UTC
When deleting a Tale that's running, the page doesn't re-direct and you're left with an un-selected Tale _and_ the running instance.

### Steps to Reproduce
1. Launch a Tale
1. Navigate to its Run page
1. Delete the Tale
1. Note that the instance is still embedded in the browser

![demo](https://user-images.githubusercontent.com/9289652/59632119-4548c280-90fe-11e9-8041-cafab0f16ab4.gif)

**Comment by bodom0015** [comment] 2019-06-18 16:05
I believe that I have seen this before as well, but am unable to figure out the root cause of what's happening there. It's also worth noting that once #459 is merged, this will be fixed regardless.

I had previously added a spinner with a delay there #447, and I believe that helped slightly with #213 but appears to have not helper with this one - I have proposed previously that this issue should be fixed on the server-side by adding an `InstanceStatus.DELETING` or similar.

_______________________________

*Verbose Details*

If you check the console when you're in this state, it's very likely that it's the same stack trace as #395. We see this occasionally when deleting an `EmberObject` from the server, and the cache in Ember-Data's store becomes out-of-sync. Ember-Data attempts to do a `backgroundReload` or `reload` of a model that has been deleted from the server, and it gets confused and throws an error.

Since we are already using Ember-Data's `destroyRecord` in most cases, I am not sure how to further signal to the Ember-Data store that a model needs to be purged from its cache and that further queries for the model should be stopped.

It's possible that something about the asynchronous cleanup required by our `DELETE /instance/:id` code is confusing Ember, which perhaps expects that once `.destroyObject()` returns, the model should be deleted.

**Comment by bodom0015** [comment] 2019-10-08 20:42
This should finally be resolved by https://github.com/whole-tale/girder_wholetale/pull/357 and the related UI change within #550

**Closed by bodom0015** 2019-10-08 20:42 UTC
Labels: bug
